package com.example.composechatexample.ui.theme

import androidx.compose.ui.graphics.Color
val Primary = Color(0xFF006497)
val PrimaryContainer = Color(0xFFcce5ff)
val Secondary = Color(0xFF51606f)
val SecondaryContainer = Color(0xFFd4e4f6)
val Tertiary = Color(0xFF66587b)
val TertiaryContainer = Color(0xFFeddcff)
val Error = Color(0xFFba1a1a)
val Background = Color(0xFFfcfcff)
val OnBackground = Color(0xFF1a1c1e)
val Neutral = Color(0xFF8f9194)
val OnPrimary = Color(0xffffffff)
val OnPrimaryContainer = Color(0xff001e31)
val OnSecondaryContainer = Color(0Xff0d1d2a)
val OnTertiaryContainer = Color(0XFF221534)
val OnSurfaceVariant = Color(0xffc2c7ce)
val OnError = OnPrimary
val OnSecondary = OnPrimary
val OnTertiary = OnPrimary
val SurfaceVariant = Color(0xffdee3eb)

val DarkPrimary = Color(0xFF91ccff)
val DarkPrimaryContainer = Color(0xFF004b73)
val DarkSecondary = Color(0xFFb8c8da)
val DarkSecondaryContainer = Color(0xFF394857)
val DarkTertiary = Color(0xFFd1bfe7)
val DarkTertiaryContainer = Color(0xFF4e4162)
val DarkBackground = Color(0xFF1a1c1e)
val DarkError = Color(0xFFffb4ab)
val DarkOnBackground = Color(0xFFe2e2e5)
val DarkNeutral = Color(0xFF8f9194)
val DarkOnPrimary = Color(0xFF003351)
val DarkOnPrimaryContainer = Color(0xffcce5ff)
val DarkOnSecondaryContainer = Color(0Xffd4e4f6)
val DarkOnTertiaryContainer = Color(0XFFecdcff)
val DarkSurfaceVariant = Color(0xff8c9198)
val DarkOnSurfaceVariant = Color(0xffc2c7ce)
val DarkOnError = Color(0xFF690005)
val DarkOnSecondary = Color(0xFF23323f)
val DarkOnTertiary = Color(0xFF372a4a)
